apiVersion: v1
kind: Service
metadata:
  name: rasp-gateway-service
  namespace: rasp-pi
spec:
  type: NodePort
  ports:
    - nodePort: 31319
      port: 4000
      targetPort: 4000
  selector:
    app: rasp-gateway
