apiVersion: v1
kind: Service
metadata:
  name: rasp-frontend-service
  namespace: rasp-pi
spec:
  type: NodePort
  ports:
    - nodePort: 31318
      port: 3000
      targetPort: 3000
  selector:
    app: rasp-frontend
