apiVersion: v1
kind: Service
metadata:
  name: rasp-database-service
  namespace: rasp-pi
spec:
  selector:
    app: rasp-database
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
